# Example configuration file

# The config version, do not change this manually
version: 0

# List of relay endpoints
endpoints:
  - listen: 0.0.0.0:8080
    target: 127.0.0.1:80
    options:
      # Whether to enable zero-copy IO copying using splice(2).
      #
      # Default: true.
      splice: true
      # IP TOS (Type of Service) value for accepted connections / outgoing
      # connections to the target, can be null to use system default.
      #
      # Default: null.
      tos: null
      # Whether to enable TCP Fast Open (TFO) on the listening socket / outgoing
      # connections to the target.
      #
      # Default: false.
      tfo: false
      # Whether to accept a PROXY protocol (v2) header on incoming connections.
      #
      # Default: false.
      accept_proxy_protocol: false
      # Whether to require a PROXY protocol (v2) header on incoming connections.
      #
      # Default: true.
      require_proxy_protocol: true
      # PSK for encrypting the PROXY protocol (v2) header.
      #
      # Since expose the actual target address to public may lead to security
      # issues, it is recommended to set a PSK here to encrypt the header.
      # Can be null to disable encryption.
      #
      # Default: null.
      proxy_protocol_header_encryption_psk: null
